---
# Enable creating tokenreviews
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sa-default-rbac
  labels:
    app: assisted-ui-single
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: default
  namespace: assisted-ui-single
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: assisted-ui-single
  name: assisted-ui-single
  namespace: assisted-ui-single
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: assisted-ui-single
  template:
    metadata:
      labels:
        app: assisted-ui-single
    spec:
      containers:
      - name: assisted-ui-single
        image: quay.io/mlibra/assisted-ui-single:latest
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
        imagePullPolicy: Always
        ports:
          - name: ui
            containerPort: 9443
            protocol: TCP
        volumeMounts:
          - name: serving-cert
            mountPath: "/var/serving-cert"
            readOnly: true
#        livenessProbe:
#          failureThreshold: 1
#          httpGet:
#            path: /livenessProbe
#            port: ui
#            scheme: HTTPS
#          initialDelaySeconds: 10
#          periodSeconds: 10
#          successThreshold: 1
#          timeoutSeconds: 1
#        readinessProbe:
#          failureThreshold: 1
#          httpGet:
#            path: /readinessProbe
#            port: ui
#            scheme: HTTPS
#          periodSeconds: 10
#          successThreshold: 1
#          timeoutSeconds: 1
        resources:
          requests:
            cpu: 3m
            memory: 40Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
        seccompProfile: 
          type: RuntimeDefault 
      terminationGracePeriodSeconds: 15
      volumes:
        - name: serving-cert
          secret:
            secretName: assisted-ui-single
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: assisted-ui-single
  name: assisted-ui-single
  namespace: assisted-ui-single
spec:
  port:
    targetPort: https
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: reencrypt
  to:
    kind: Service
    name: assisted-ui-single
  wildcardPolicy: None
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: assisted-ui-single
  name: assisted-ui-single
  namespace: assisted-ui-single
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: assisted-ui-single
spec:
  internalTrafficPolicy: Cluster
  selector:
    app: assisted-ui-single
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 9443
  sessionAffinity: None
  type: ClusterIP
