export const SINGLE_CLUSTER_ENABLED_FEATURES = {
  ASSISTED_INSTALLER_SNO_FEATURE: false,
  ASSISTED_INSTALLER_OCS_FEATURE: false,
  ASSISTED_INSTALLER_ODF_FEATURE: false,
  ASSISTED_INSTALLER_CNV_FEATURE: true,
  ASSISTED_INSTALLER_NETWORK_TYPE_SELECTION_FEATURE: false,
  ASSISTED_INSTALLER_PLATFORM_INTEGRATION_FEATURE: false,

  // TODO(mlibra): enable ARM
};

export const ROUTE_BASE_PATH = '';
